Improvement/dandydeveloper/support multi release
Viasat/opendistro-elastic-community pull request #10
Opened 2019-11-21 08:16 UTC by DandyDeveloper

*Issue #, if available:*
None

*Description of changes:*
Support for additional clients, separate from ingestion clients. 

For ex, we like to have query clients for managing our internal calls and Kibana stuff, to avoid interfering with the tasks managed by the ingestion clients. 

This just adds an override for the clients, which can be exposed using a different ingress.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2019-11-22 00:17 UTC, DerekHeldtWerle requested changes
Hey @DandyDeveloper, thanks for another PR! I've added some minor nitpick comments related to the docs.

I'm having some trouble deploying this without adding the `discoveryOverride` changes from the data statefulset to the client deployment. I may be misunderstanding exactly how you are deploying it on your end though. Would you mind sharing the relevant portion of your config?

Last thing would be to bump the chart version 🙂

2019-11-22 00:17 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/README.md
> +#### Client.selectorOverride Explaination
Explaination -> Explanation

2019-11-22 00:17 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/README.md
> +By default, these clients will be added and load balanced via the "client" service. This override allows a separate set of clients to be deployed for different purposes (I.E. Kibana querying)
I think the proper abbreviation would be `e.g.` if the intention is for it to be `for example`.

2019-11-22 00:17 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/README.md
> +| `elasticsearch.client.selectorOverride`                   | Override for selector on client. Explained [here](#clientselectoroverride-explaination)
To match other empty variables, do you mind setting the default value to `""` instead of `null`? In a future PR we can address the lack of `""` for all string values in the `values.yaml` to match what you did with your hot/warm [PR](https://github.com/DandyDeveloper/opendistro-elastic-community/blob/309221ef4e67359bf1ec6d14291b5a34e279690d/open-distro-elasticsearch-kubernetes/helm/opendistro-es/values.yaml#L112) and to be more consistent across the board.

2019-11-22 00:17 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/opendistro-es/values.yaml
> +    selectorOverride:
`selectorOverride: ""`

2019-12-10 06:34 UTC, DandyDeveloper commented
@DerekHeldtWerle Sorry for the delay, jumping on this today. I think the discoveryOverride needed a small tweak. I'll add it here.

2019-12-10 06:46 UTC, DandyDeveloper commented
@DerekHeldtWerle Double checked. My use case didn't cater for people using discoveryOverride without an already present release. 

The assumption was this would only be used for a secondary deployment of clients. For example, I want queries managed by Kibana over a dedicated set of clients, rather then having the existing flooded clients managing queries as well. 

Question for you: What do we want to do in this scenario? Because the issue is, this is only needed for secondary client releases. It's pretty niche use-case but not uncommon. 

I could make it clearer in the documentation?

2019-12-25 03:09 UTC, DandyDeveloper commented
@DerekHeldtWerle Can I get your input?

2020-01-03 19:43 UTC, DerekHeldtWerle commented
Hey @DandyDeveloper sorry for the delay, been out for the holidays. In order to increase overall flexibility I think adding the same option for the `discoveryOverride` to the client as done with the data statefulsets would be the preferred approach as this would allow users to add this to their cluster after the original deployment:

```
        - name: discovery.seed_hosts
          value: {{ .Values.elasticsearch.discoveryOverride | default (printf "%s-discovery" (include "opendistro-es.fullname" .)) | qu
ote }}
```

Of note, it looks like the opendistro elasticsearch team has merged and then moved the chart to a new [repo](https://github.com/opendistro-for-elasticsearch/opendistro-build). I'm more than happy to merge this PR into this repo, but I imagine other users may benefit from this in the new location as well if you wanted to open it there as well.

2020-01-06 00:12 UTC, DandyDeveloper commented
@DerekHeldtWerle I agree. I'll add this in as anew PR on the other repo.

2020-01-06 06:32 UTC, DandyDeveloper commented
Closing in favour of https://github.com/opendistro-for-elasticsearch/opendistro-build/pull/49

2020-01-06 06:32 UTC, closed without merging