Support Hot/Warm Archicture Better
Viasat/opendistro-elastic-community pull request #5
Opened 2019-07-10 01:52 UTC by DandyDeveloper

My original implementation didn't fully consider this scenario. 

By default, for hot/warm you add an aliased release. The problem is this has no discovery service / uses a different template name. This override allows the user for hot/warm to define the cluster discovery service for extra deployments.

2019-07-10 01:52 UTC, DandyDeveloper commented
/assign @dkavanagh

2019-07-11 21:14 UTC, kalvinnchau commented
Hey @DandyDeveloper! Thanks for the PR! 
It's just @DerekHeldtWerle and I that are maintaining this repo at the moment, we're gonna test it out in our cluster and then we'll get this merged.

2019-07-17 20:28 UTC, DerekHeldtWerle commented
Hey @DandyDeveloper this is great! Would you mind adding a section to the README about how to deploy the hot/warm architecture (e.g. a basic example _warm/code_ `values.yml` file) and detail which values are required and why that's the case? This'll help alleviate the number of future inquires into why a users installation may or may not be supported in their setup/environment.

2019-07-18 00:48 UTC, DandyDeveloper commented
@DerekHeldtWerle Done. Can you take a look?

2019-07-18 03:15 UTC, DerekHeldtWerle requested changes
Just some very minor things, but otherwise looks great!

2019-07-18 03:15 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/README.md
> +*Note that the config is a snippet showing how you would enable index routing. Please find the [full configuration example here](#elasticsearch.yml-Config)*
`(#elasticsearch.yml-Config)` -> `(#elasticsearchyml-config)`

2019-07-18 03:15 UTC, DerekHeldtWerle commented on open-distro-elasticsearch-kubernetes/helm/README.md
> +After the `requirements.yaml` is configured. Another instance of the chart can be defined in the `values.yaml` to provide the details of the warm environment. The benefit to using the alias attribute
`configured. Another` -> `configured, another`

2019-07-18 04:53 UTC, DandyDeveloper commented
@DerekHeldtWerle Done!

2019-07-18 10:42 UTC, merged